steps:
  - name: "node"
    entrypoint: "npm"
    args: ["install"]
  # Build the frontend
  - name: "node"
    entrypoint: "npm"
    args: ["run", "build"]
    env:
      - "NODE_OPTIONS=--openssl-legacy-provider"
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_CLOUD_RUN_APP_NAME", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$_CLOUD_RUN_APP_NAME"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$_CLOUD_RUN_APP_NAME",
        "--image",
        "gcr.io/$PROJECT_ID/$_CLOUD_RUN_APP_NAME",
        "--region",
        "$_CLOUD_RUN_REGION",
      ]
timeout: 1800s
substitutions:
  _CLOUD_RUN_APP_NAME: "the-tuul"
  _CLOUD_RUN_REGION: "us-central1"
images:
  - gcr.io/$PROJECT_ID/the-tuul
